name: test-github-action
run-name: ${{ github.actor }} is trying out GitHub Actions
on: [push]
jobs:
  check-mockery-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go install github.com/vektra/mockery/v2@latest
      - run: mockery --version
